project:
  type: website

website:
  title: "Fabrizio Damicelli"
  favicon: /images/favicon-32x32.png
    # twitter-card: true
    # open-graph: true
  site-url: https://fabridamicelli.github.io
  description: ""
  navbar:
    left:
      - file: index.qmd
        text: About
          # icon: house
      - file: blog.qmd
        text: Blog
      - file: code.qmd
        text: Open Source
          # icon: github
      - file: research.qmd
        text: Research
          # icon: puzzle-fill
      - text: Teaching
        href: https://fabridamicelli.github.io/python-course
      - href: https://www.youtube.com/@fabridamicelli
        text: Videos
      - file: links.qmd
        text: Links
      - file: til.qmd
        text: TIL
      # - href: https://buymeacoffee.com/fabdam
      #   text: Support
        #icon: coin

    right:
      - href: https://github.com/fabridamicelli
        icon: github
      - href: https://twitter.com/fabridamicelli
        icon: twitter
      - href: https://linkedin.com/in/fabridamicelli
        icon: linkedin
      - href: https://www.youtube.com/@fabridamicelli
        icon: youtube
      - href: blog.xml
        icon: rss

format:
  html:
    css: styles.css
    theme: cosmo
    mainfont: Inconsolata
    toc: true
    include-after-body: plausible.html
